name: Build binaries
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: |
        pip install pytest pytest-cov pyinstaller
        pip install ./
    - name: Install Samtools
      run: |
        wget https://github.com/samtools/samtools/releases/download/1.15.1/samtools-1.15.1.tar.bz2
        bunzip2 samtools-1.15.1.tar.bz2
        tar xvf samtools-1.15.1.tar
        cd samtools-1.15.1
        ./configure
        make
        cp samtools ..
        cd ..
    - name: Install readItAndKeep
      run: |
        git clone https://github.com/GenomePathogenAnalysisService/read-it-and-keep.git
        cd read-it-and-keep/src
        make
        mv readItAndKeep ../..
        cd ../..
        rm -r read-it-and-keep
    # - name: Test with pytest
    #   env:
    #     GPAS_SAMTOOLS_PATH: ./samtools
    #     GPAS_READITANDKEEP_PATH: ./readItAndKeep
    #   run: |
    #     pytest --exitfirst --verbose --failed-first \
    #     --cov=. --cov-report html tests/test_gpas.py
    - name: Build PyInstaller binary
      # run: |
      #  pyinstaller --onefile --name cli-upload --add-data src/gpas/data:data --noconfirm src/gpas/cli-upload.py
      run: |
        pyinstaller cli-upload.spec
    - name: Copy files into dist/
      run: |
        cp readItAndKeep dist/
        cp samtools dist/
    - name: Test binary
      run: |
        dist/cli-upload tests/test-data/large-illumina-bam.csv --processes 1
    - name: Store dist
      uses: actions/upload-artifact@v2
      with:
        name: cli-upload-${{ matrix.os }}
        path: dist/*
        
